# Generated by Django 4.2.1 on 2023-07-19 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='url',
        ),
        migrations.AddField(
            model_name='url',
            name='full_url',
            field=models.CharField(default=1, max_length=1000, unique=True),
            preserve_default=False,
        ),
    ]
